### ISSUE TITLE
Need to account for spaces in TV Shows in findAll()

### ISSUE THREAD

**Issue by llewrek** [rueckstiess/py-plex#1]
First of all, thank you for creating this. I was so relieved to find that someone had written a Python wrapper for Plex!

Your findAll method in library.py creates a query by appending the given name at the end of the query string. This works for TV shows that have single-word names, but fails when the TV show's name contains spaces. Just replace the spaces in the name with %20 and you should be good to go.

**Comment by rueckstiess** [comment]
Hi, thanks for the info. I can't currently test this as I'm travelling. Would you be able to make a pull request that fixes the problem? 

By the way, I haven't worked much on this for a while now and it's just been a hobby project. So sorry if there are any more bugs or problems :-)

Thanks,
Thomas
